<a href="https://colab.research.google.com/github/parker533/Hello_Net/blob/master/Numpy_and_Pandas_Review_from_Book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Numpy*


1) Before numpy there was numeric and numarray. Don't use them because those are old.

2)Numpy works with arrays, arrays are homogeneous because all the elements in it are the same type and the same size so the dtype of the whole array or the d-type of an element inside the array are the same.

3)Its dimensions and number of items are known as its shape.

4)Each dimention is known as axes and the number of dimentions is known as rank

5) Another thing is their size are fixed. This means with you want to add something to it you have to create a separate array for it.







In [ ]:
import numpy as np
a = np.array([1,2,4,6])
print(a)
print(type(a))# tells if it is a numpy array
print(a.dtype)# tells the datatype it is made off
print(a.size)# cuts through the brackets regardless of the dimensions and tells you the element number
print(a.ndim)# tells you many axes/rank/levels of square brackets wrapped around
print(a.shape)# tells you how many things are in each square bracket

[1 2 4 6]
<class 'numpy.ndarray'>
int64
4
1
(4,)


In [ ]:
b = np.array([[1.3,2.4],[0.3,4.1]])
#These things are just used for gathering information on an array
print(b)
print(b.dtype)
print(b.ndim)
print(b.size)# see it gave the total
print(b.shape)
print(b.itemsize)# This tells you the amount of space each element takes in byte

[[1.3 2.4]
 [0.3 4.1]]
float64
2
4
(2, 2)
8


In [ ]:
from numpy.core.multiarray import dtype
import numpy as np
#Creating an array
#np.array accepts tuples too, it can also accept a mixture of tuples and list
#If you have an array made up of str dtype then to get the dtype use a.dtype.name not just a.dtype
# You can change the dtype using the dtype parameter
b = np.array([[1.3,2.4],[0.3,4.1]],dtype= float)
print(b)
print(b.dtype)
#INTRINSIC ARRAY CREATION
print(np.zeros((3,3)))
print(np.ones((3,3),dtype = int))
# in-built python range gives you a sequence of numbers which you can put into a list(shown in practice 3 notebook) but np.arange gives you a sequence of numbers in an array
c = np.arange(0,10,0.5)
d = np.linspace(0,10,5)
print(c)
print(d)
# when doing a reshape,make sure the numbers you put can multiply for you to get the range size
cc = np.arange(0,12).reshape((2,3,2))#0-12 has size 12, and 2x3x2 = 12
print(cc)
aa = np.random.rand(3,3)# random.random and random.rand are the same
print(aa)

[[1.3 2.4]
 [0.3 4.1]]
float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[ 0.   2.5  5.   7.5 10. ]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[0.99253138 0.33230731 0.06674406]
 [0.44510822 0.39299527 0.2973448 ]
 [0.23293024 0.18418002 0.938947  ]]


It turns out that dimesions/axes are the number of brackets and shape tells you whats in a brackets and not the bracket it's sels so shape(3,3) means there is one bracket with 3 smaller brackets in them and each smaller bracket has 3 things in them.

In [ ]:
#Want documentation info and help
"""
To get documentation on a funtion do"help(function)" or "function?"
Note this cuz it cost you an hour, if a function is associated with a library
import that library before you ask for help else will not work.
"""
import numpy as np
#np.arange?
#dir(np) this code gives you all the modules associated with numpy and you can explore further maybe with module name in the documentation.

In [ ]:
#BASIC OPERATIONS--> basic addition and subtructing stuff with array
#arithmetic operation
# if u add or multiply an array by one number it affects all
import numpy as np
d = np.arange(6)
print((d + 5))
'''
array by array arithmetic are elementwise, this means that if it is multiplying,
it multiply elements that are in the same position in both array and it use the
results to create a new array
'''
dd = np.ones((6,))
e = dd + d
print(e)
print(dd)
print((d * np.sin(dd)))
print(d + np.sqrt(dd))# np.sqrt is square root and not squared
'''
In most analytical tools, the * is not used for elementwise multiplication but rather a dot product
In python we use np.dot(A,B) for dot product. Not that dot product is not commutative so you cannot
switch the arrays cuz first array multiply horizontally and the second vertically
'''
a = np.dot(e,dd)
b = np.dot(dd,e)
print(a)#You got just one number because they are both 1 dimensional
print(b)


[ 5  6  7  8  9 10]
[1. 2. 3. 4. 5. 6.]
[1. 1. 1. 1. 1. 1.]
[0.         0.84147098 1.68294197 2.52441295 3.36588394 4.20735492]
[1. 2. 3. 4. 5. 6.]
21.0
21.0
